// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeStructure.Persistance;

namespace TreeStructure.Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221010211431_UpdateSeedData")]
    partial class UpdateSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TreeStructure.Domain.Entities.Leaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LeafId")
                        .HasColumnType("int");

                    b.Property<int?>("LeafParentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeafId");

                    b.HasIndex("ParentId");

                    b.ToTable("Leafs");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            Name = "FirstLeaf",
                            ParentId = 11
                        },
                        new
                        {
                            Id = 22,
                            Name = "SecondLeaf",
                            ParentId = 11
                        },
                        new
                        {
                            Id = 23,
                            Name = "ThirdLeaf",
                            ParentId = 12
                        },
                        new
                        {
                            Id = 24,
                            LeafParentId = 23,
                            Name = "FourthLeaf",
                            ParentId = 12
                        });
                });

            modelBuilder.Entity("TreeStructure.Domain.Entities.TreeNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("TreeNodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TreeNodeId");

                    b.ToTable("Nodes");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Name = "FirstNode",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 12,
                            Name = "SecondNode",
                            ParentId = 11
                        },
                        new
                        {
                            Id = 13,
                            Name = "ThirdNode",
                            ParentId = 11
                        },
                        new
                        {
                            Id = 14,
                            Name = "FourthNode",
                            ParentId = 12
                        });
                });

            modelBuilder.Entity("TreeStructure.Domain.Entities.Leaf", b =>
                {
                    b.HasOne("TreeStructure.Domain.Entities.Leaf", null)
                        .WithMany("LeafsChildren")
                        .HasForeignKey("LeafId");

                    b.HasOne("TreeStructure.Domain.Entities.TreeNode", "Parent")
                        .WithMany("Leafs")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TreeStructure.Domain.Entities.TreeNode", b =>
                {
                    b.HasOne("TreeStructure.Domain.Entities.TreeNode", null)
                        .WithMany("Nodes")
                        .HasForeignKey("TreeNodeId");
                });

            modelBuilder.Entity("TreeStructure.Domain.Entities.Leaf", b =>
                {
                    b.Navigation("LeafsChildren");
                });

            modelBuilder.Entity("TreeStructure.Domain.Entities.TreeNode", b =>
                {
                    b.Navigation("Leafs");

                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
